### PR TITLE
Fix mountpoint detection

### LINKED ISSUE #138: autoenv is broken in zsh
I just installed autoenv, and after sourcing ~/.autoenv/activate.sh the shell hangs until sending interrupt signal (ctrl-C).  

I executed test.sh in the tests directory, and here is the output:
```
./test.sh 
:: Running test_not_file for bash...Success.
:: Running test_custom_filename for bash...Success.
:: Running test_symlink for bash...Success.
:: Running test_simple for bash...Success.
:: Running test_cd_spaces for bash...Success.
:: Running test_colons for bash...Success.
:: Running test_doubleslash for bash...Success.
:: Running test_cd_env for bash...Success.
:: Running test_noclobber for bash...Success.
:: Running test_auth_spaces for bash...Success.
:: Running test_not_file for zsh...
^CFail.
Fail.
:: Output of last test:

:: Output of last test:

```

### LINKED ISSUE #139: Autoenv stuck in infinite loop
Autoenv at 644903c works fine for me but latest versions produce what looks like an infinite loop, as my terminal is stuck when launched and does't give me a prompt.

I was waiting for #136 to be merged, unfortunately 3888c0b is still stuck in infinite loops.

This was reproduced on two machines running OSX 10.11.6 with [my custom `dotfiles`](https://github.com/kdeldycke/dotfiles).

I'm going to update this ticket with new findings as I continue my investigations.

### PR DESCRIPTION
**Pull request by dasJ**
I hope this:
- Closes #138
- Closes #139

All tests work on Linux with the most recent versions of all shells.
Can someone confirm this for Darwin and distributions with older shell versions as well?

### CODE REVIEW

**Comment by kdeldycke** [comment]
Still the same nasty loop on OSX 10.11.6 an the following bash release from Homebrew:

```shell
$ bash --version
GNU bash, version 4.3.46(1)-release (x86_64-apple-darwin15.5.0)
```

Here is a fresh execution trace with your `https://github.com/dasJ/autoenv` fork:
```shell
++ AUTOENV_AUTH_FILE=/Users/kdeldycke/.autoenv_authorized
++ AUTOENV_ENV_FILENAME=.env
++ which gsha1sum
++ enable_autoenv
++ cd /Users/kdeldycke/dotfiles/dotfiles-common
++ autoenv_cd /Users/kdeldycke/dotfiles/dotfiles-common
++ command -v chdir
++ builtin cd /Users/kdeldycke/dotfiles/dotfiles-common
++ '[' 0 -eq 0 ']'
++ autoenv_init
++ local _mountpoint _files _orderedfiles _sedregexp
++ '[' 15 '!=' darwin15 ']'
++ _sedregexp=-E
+++ df -Th /Users/kdeldycke/dotfiles/dotfiles-common
+++ awk 'END{print $NF}'
++ _mountpoint=
+++ echo /Users/kdeldycke/dotfiles/dotfiles-common
+++ sed -E s:/+:/:g
++ PWD=/Users/kdeldycke/dotfiles/dotfiles-common
++ command -v chdir
++ builtin cd /Users/kdeldycke/dotfiles/dotfiles-common
+++ _hadone=
++++ pwd -P
+++ '[' /Users/kdeldycke/dotfiles/dotfiles-common '!=' '' ']'
++++ pwd -P
+++ _file=/Users/kdeldycke/dotfiles/dotfiles-common/.env
+++ '[' -f /Users/kdeldycke/dotfiles/dotfiles-common/.env ']'
+++ command -v chdir
++++ pwd -P
+++ builtin cd /Users/kdeldycke/dotfiles/dotfiles-common/..
++++ pwd -P
+++ '[' /Users/kdeldycke/dotfiles '!=' '' ']'
++++ pwd -P
+++ _file=/Users/kdeldycke/dotfiles/.env
+++ '[' -f /Users/kdeldycke/dotfiles/.env ']'
+++ command -v chdir
++++ pwd -P
+++ builtin cd /Users/kdeldycke/dotfiles/..
++++ pwd -P
+++ '[' /Users/kdeldycke '!=' '' ']'
++++ pwd -P
+++ _file=/Users/kdeldycke/.env
+++ '[' -f /Users/kdeldycke/.env ']'
+++ command -v chdir
++++ pwd -P
+++ builtin cd /Users/kdeldycke/..
++++ pwd -P
+++ '[' /Users '!=' '' ']'
++++ pwd -P
+++ _file=/Users/.env
+++ '[' -f /Users/.env ']'
+++ command -v chdir
++++ pwd -P
+++ builtin cd /Users/..
++++ pwd -P
+++ '[' / '!=' '' ']'
++++ pwd -P
+++ _file=//.env
+++ '[' -f //.env ']'
+++ command -v chdir
++++ pwd -P
+++ builtin cd //..
++++ pwd -P
+++ '[' // '!=' '' ']'
++++ pwd -P
+++ _file=///.env
+++ '[' -f ///.env ']'
+++ command -v chdir
++++ pwd -P
+++ builtin cd ///..
++++ pwd -P
+++ '[' / '!=' '' ']'
++++ pwd -P
+++ _file=//.env
+++ '[' -f //.env ']'
+++ command -v chdir
++++ pwd -P
+++ builtin cd //..
++++ pwd -P
+++ '[' // '!=' '' ']'
++++ pwd -P
+++ _file=///.env
+++ '[' -f ///.env ']'
+++ command -v chdir
++++ pwd -P
+++ builtin cd ///..
++++ pwd -P
+++ '[' / '!=' '' ']'
++++ pwd -P
+++ _file=//.env
+++ '[' -f //.env ']'
+++ command -v chdir
++++ pwd -P
+++ builtin cd //..
++++ pwd -P
+++ '[' // '!=' '' ']'
++++ pwd -P
+++ _file=///.env
+++ '[' -f ///.env ']'
+++ command -v chdir
++++ pwd -P
+++ builtin cd ///..
++++ pwd -P
+++ '[' / '!=' '' ']'
++++ pwd -P
+++ _file=//.env
+++ '[' -f //.env ']'
+++ command -v chdir
++++ pwd -P
+++ builtin cd //..
++++ pwd -P
+++ '[' // '!=' '' ']'
++++ pwd -P
+++ _file=///.env
+++ '[' -f ///.env ']'
+++ command -v chdir
++++ pwd -P
+++ builtin cd ///..
++++ pwd -P
+++ '[' / '!=' '' ']'
(...)
```

**Comment by dirk-olmes** [comment]
Same behavior on CentOS

GNU bash, version 4.1.2(1)-release (i386-redhat-linux-gnu)

**Comment by dirk-olmes** [comment]
Ah, I wasn't looking at the output closely enough. It works on CentOS, albeit the cd still seemed to be stuck because I had rm aliased to "rm -i"

**Comment by kdeldycke** [comment]
Just found the culprit it was a left-over alias in my `.bash_profile` messing up with the default output of `df`. Here it is: https://github.com/kdeldycke/dotfiles/blob/3f9be88cf09fd186da32b6856bd58ba5e01fc388/dotfiles-common/.bash_profile#L98

Removing that line and using this PR makes `.autoenv` works fine again. Thanks @dirk-olmes for the heads up! :sweat_smile:

Now my bash-fu is not up to your level, but isn't there a way to disable all user-defined aliases in a script, so that we'll avoid a wide class of false bug reports?

**Comment by dasJ** [comment]
@kdeldycke Well, I can prefix all commands with `\`, I think I'll do that soon

**Pull request merged**
