### PR TITLE
Avoid crash with zsh 5.1.x

### LINKED ISSUE #87: Segfaults when used with ZSH 5.1
I refer to https://github.com/robbyrussell/oh-my-zsh/issues/4346#issuecomment-147018190, which discusses a crash when using autoenv in ZSH (specifically with oh-my-zsh also).

Do you think you can provide the fix suggested there?

### PR DESCRIPTION
**Pull request by gionn**
Fix #87 

Did some tests and it seems working.

### CODE REVIEW

**Comment by dasJ** [comment]
I can not really merge this because it might override the user-defined value of -a.

Do you know why the already implemented method does not work?

**Comment by gionn** [comment]
Nope, just pulled latest master, zsh 5.1.1-1ubuntu2 on Ubuntu 16.04 still crash while hitting tab after entering a directory with .env.

If you think it's better, we can check if the zsh version is the affected one and apply the workaround only when needed (better override -a than cause a shell segfault).

**Comment by gionn** [comment]
@dasJ now fix is only applied to bugged version (5.1.*)

**Comment by dasJ** [comment]
@gionn Can you verify that it also works with the dash version?

PR: https://github.com/kennethreitz/autoenv/pull/113

**Pull request merged**
