### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by erinxocon**
added source /usr/local/opt/autoenv/activate.sh since that is what brew tells you to do

### CODE REVIEW

**Comment by kennethreitz** [comment]
I think this is a negative change, not a positive one — but I am not positive

**Comment by kennethreitz** [comment]
did brew remove the ability to install to a different location?

**Comment by erinxocon** [comment]
I don't know maybe, that's just what autoenv tells me to do after you install it with brew

**Comment by kennethreitz** [comment]
that's because homebrew is smart :)

**Pull request closed without merging**
