### PR TITLE
Add ability to run commands when exiting a directory.

### PR DESCRIPTION
**Pull request by ijcd**
Fixes Issue #30

### CODE REVIEW

**Comment by calvinchengx** [comment]
Is this merged already? I need this feature as well.

**Comment by dasJ** [comment]
+1

**Comment by fushi** [comment]
Can we either get this merged, or denied? Seeing it sit in limbo like this is saddening.

**Comment by jakesherman** [comment]
+1

**Comment by fjsj** [comment]
+1

**Comment by Futurile** [comment]
@ijcd does this work with bash? I'm seeing it try to execute both the .autoenv and the .unenv when I change into the directory (see below). When I'm changing out of the project dir it doesn't seem to call .unenv. 

```bash
$ cd py3-datavis/
running env
deactivating
deactivate: command not found
deactivating
deactivate: command not found
deactivating
(py3-datavis):~/workspace/py3-datavis$ 
````
My .autoenv:
````bash
echo "running env"
workon py3-datavis
````
My .unenv
````bash
echo "deactivating"
deactivate
````

**Comment by fjsj** [comment]
why it was closed :cry: ?

**Comment by Futurile** [comment]
@fjsj It's clear Kenneth has decided this is out of scope (it was in limbo for a while, when I bumped it he closed it). Fair enough, it's his tool.

I'm using Direnv which supports this functionality - I wrote a post about [automating environment set-up with direnv](http://www.futurile.net/2016/02/03/automating-environment-setup-with-direnv/) if you're interested.

**Pull request closed without merging**
