### PR TITLE
Only one char needs to be read.

### PR DESCRIPTION
**Pull request by silencej**
This saves two RET typing. I was ssh from windows MSYS environment to ArchLinux in using autoenv.

### CODE REVIEW

**Comment by dasJ** [comment]
The question is: Does this work on darwin as well? The -n parameter is not specified by [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/read.html#tag_20_109) (as far as I can tell).

**Comment by dasJ** [comment]
I found this ugly way instead: http://stackoverflow.com/a/8732057/1432545

**Comment by silencej** [comment]
I see. Not easy for a POSIX-compliant way.

**Comment by dasJ** [comment]
I'm sorry, I accidentially reopened this

**Pull request closed without merging**
